matrix:
  include:
    - language: python
      python:
        - "3.7"
      cache: pip
      install:
        - pip install pylint
      script:
        - pylint --disable=E0401 **/*.py
        
    - language: php
      php:
        - 7.0
      script:
        - npm i -g phplint
        - phplint '**/*.php'
        
    - language: node_js
      node_js:
        - 10
      script:
        - npm i -g jshint
        - jshint 'javascript'
